package marcostar.project.store_project.entities.enums;

public enum TypePrivilege {
    ACCESS_TO_DASHBOARD,
    CREATE_USER,
    READ_USER,
    SHOW_DETAIL_USER,
    UPDATE_USER,
    CHANGE_PASSWORD_USER,
    SUSPEND_USER,
    DELETE_USER,
    CREATE_ORGANIZATION_USER,
    READ_ORGANIZATION_USER,
    UPDATE_ORGANIZATION_USER,
    DELETE_ORGANIZATION_USER,

    CREATE_ROLE,
    READ_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,
    ASSIGN_ROLE_TO_USER,

    CREATE_PRIVILEGE,
    READ_PRIVILEGE,
    UPDATE_PRIVILEGE,
    DELETE_PRIVILEGE
}
